loaders:
  - type: deepstack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../deepstack/components/connectors]
    modules: ["openapi_service"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: deepstack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Various connectors to integrate with external services.
  category_slug: deepstack-api
  title: Connectors
  slug: connectors-api
  order: 15
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: connectors_api.md
