blank_issues_enabled: true
contact_links:
  - name: Something unclear? Just ask :)
    url: https://github.com/khulnasoft/deepstack/discussions/new
    about: Start a Github discussion with your question
